name: testing_env
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip

  - gdal
  - rasterstats
  - earthengine-api
  - fiona
  - pandas
  - seaborn>=0.12.0
  - google-cloud-storage
  - setuptools
  - requests
  - pytest